"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport } from "ai";

import { Button } from "@/components/ui/button";
import { ChatMessage } from "@/features/chat/components/chat-message";
import { cn } from "@/lib/utils";

export function ChatInterface() {
  // useState keeps the controlled textarea value in the browser between renders.
  const [input, setInput] = useState("");

  // useMemo creates the transport once, preventing a new API client on every render.
  const transport = useMemo(
    () => new DefaultChatTransport({ api: "/api/chat" }),
    []
  );

  // useChat owns message history and updates it as the API stream delivers chunks.
  const { messages, sendMessage, status, stop, error } = useChat({ transport });
  const isGenerating = status === "submitted" || status === "streaming";
  const latestMessage = messages.at(-1);
  const hasAssistantText =
    latestMessage?.role === "assistant" &&
    latestMessage.parts.some(
      (part) => part.type === "text" && part.text.trim().length > 0
    );

  // Keep the indicator visible from submission until Claude's first text token
  // reaches the UI. This prevents a status change from causing a visual flash.
  const showThinkingIndicator = isGenerating && !hasAssistantText;

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const text = input.trim();
    if (!text || isGenerating) {
      return;
    }

    // Clear immediately for responsive feedback; useChat stores the submitted message.
    setInput("");
    await sendMessage({ text });
  }

  return (
    <div className="overflow-hidden rounded-xl border bg-card shadow-sm">
      <div
        aria-live="polite"
        aria-label="Conversation"
        className="min-h-80 space-y-4 p-4 sm:p-6"
      >
        {messages.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            Try asking: “What technologies do you use?”
          </p>
        ) : (
          messages.map((message) => (
            <ChatMessage key={message.id} message={message} />
          ))
        )}

        <div
          aria-hidden={!showThinkingIndicator}
          className={cn(
            "overflow-hidden transition-[max-height,opacity,transform] duration-200 ease-out",
            showThinkingIndicator
              ? "max-h-10 translate-y-0 opacity-100"
              : "max-h-0 -translate-y-1 opacity-0"
          )}
        >
          <p
            className="flex items-center gap-2 text-sm text-muted-foreground"
            role={showThinkingIndicator ? "status" : undefined}
          >
            <span className="inline-flex gap-1" aria-hidden="true">
              <span className="size-1.5 animate-pulse rounded-full bg-current" />
              <span className="size-1.5 animate-pulse rounded-full bg-current [animation-delay:150ms]" />
              <span className="size-1.5 animate-pulse rounded-full bg-current [animation-delay:300ms]" />
            </span>
            Thinking…
          </p>
        </div>

        {error && (
          <p className="text-sm text-destructive" role="alert">
            Something went wrong. Please try again.
          </p>
        )}
      </div>

      <form className="border-t p-4 sm:p-6" onSubmit={handleSubmit}>
        <label className="sr-only" htmlFor="chat-message">
          Ask a question
        </label>
        <textarea
          id="chat-message"
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder="Ask about my work or engineering approach…"
          rows={3}
          disabled={isGenerating}
          className="w-full resize-y rounded-lg border bg-background px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50"
        />

        <div className="mt-3 flex items-center justify-between gap-3">
          <p className="text-xs text-muted-foreground">
            Responses are generated by AI and may be incomplete.
          </p>
          {isGenerating ? (
            <Button type="button" variant="outline" onClick={stop}>
              Stop
            </Button>
          ) : (
            <Button type="submit" disabled={!input.trim()}>
              Send
            </Button>
          )}
        </div>
      </form>
    </div>
  );
}
